/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CustomerId = Principal;
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'paymentStatus' : string,
  'createdAt' : bigint,
  'totalAmount' : bigint,
  'customerId' : CustomerId,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Product {
  'id' : ProductId,
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'price' : bigint,
  'supplierId' : SupplierId,
  'images' : Array<ExternalBlob>,
}
export type ProductId = string;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SupplierId = Principal;
export interface SupplierProfile {
  'id' : SupplierId,
  'contactInfo' : string,
  'name' : string,
  'description' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'isSupplier' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[string, string, bigint, bigint], ProductId>,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[Array<OrderItem>, bigint], string>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSuppliers' : ActorMethod<[], Array<SupplierProfile>>,
  'getCallerSupplierProducts' : ActorMethod<[], Array<Product>>,
  'getCallerSupplierProfile' : ActorMethod<[], [] | [SupplierProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSupplier' : ActorMethod<[SupplierId], [] | [SupplierProfile]>,
  'getSupplierProducts' : ActorMethod<[SupplierId], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'registerSupplier' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateExistingSupplier' : ActorMethod<
    [string, string, string],
    SupplierProfile
  >,
  'updateOrderStatus' : ActorMethod<[string, string], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, bigint, bigint],
    undefined
  >,
  'updateProductStock' : ActorMethod<[ProductId, bigint], undefined>,
  'updateSupplier' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];